import { createRemixStub } from '@remix-run/testing/dist/create-remix-stub'
import type { Meta, StoryObj } from '@storybook/react'

import ProductWithFilters from './ProductWithFilters'

const meta = {
  title: 'Sections/ProductWithFilters',
  component: ProductWithFilters,
  tags: ['autodocs'],
  parameters: {
    layout: 'fullscreen',
  },
  args: {
    locked: false,
    filters: [
      {
        type: 'multichoice',
        label: 'Brand',
        fieldName: 'subtitle',
        choices: ['Lange', 'Fischer', 'Dalbello'],
      },
    ],
    products: [
      {
        id: '1',
        name: 'Zero G',
        brand: { name: 'Dalbello', slug: 'Dalbello' },
        chips: ['Tour', 'Sci'],
        awards: [
          { name: 'green', color: 'green' },
          { name: 'pro', color: 'silver' },
        ],
        testedPreview: 'TESTED',
        firstInfo: 'Larg. centro: 64mm',
        secondInfo: 'Peso: 780gr',
        imageUrl: '/assets/mock-product-1.png',
      },
      {
        id: '2',
        name: 'Orb freebird',
        brand: { name: 'Lange', slug: 'Lange' },
        chips: ['Tour', 'Sci'],
        awards: [{ name: 'smart', color: 'silver' }],
        firstInfo: 'Larg. centro: 64mm',
        secondInfo: 'Peso: 780gr',
        imageUrl: '/assets/mock-product-2.png',
        supermatch: true,
      },
      {
        id: '3',
        name: 'Orb freebird',
        brand: { name: 'Lange', slug: 'Lange' },
        chips: ['Tour', 'Sci'],
        awards: [{ name: 'pro', color: 'silver' }],
        firstInfo: 'Larg. centro: 64mm',
        secondInfo: 'Peso: 780gr',
        imageUrl: '/assets/mock-product-3.png',
      },
      {
        id: '4',
        name: 'Zero G',
        brand: { name: 'Dalbello', slug: 'Dalbello' },
        chips: ['Tour', 'Sci'],
        awards: [
          { name: 'green', color: 'green' },
          { name: 'smart', color: 'silver' },
          { name: 'pro', color: 'silver' },
        ],
        firstInfo: 'Larg. centro: 64mm',
        secondInfo: 'Peso: 780gr',
        imageUrl: '/assets/mock-product-1.png',
        supermatch: true,
      },
      {
        id: '5',
        name: 'Orb freebird',
        brand: { name: 'Fischer', slug: 'Fischer' },
        chips: ['Tour', 'Sci'],
        awards: [
          { name: 'green', color: 'green' },
          { name: 'smart', color: 'silver' },
          { name: 'pro', color: 'silver' },
        ],
        firstInfo: 'Larg. centro: 64mm',
        secondInfo: 'Peso: 780gr',
        imageUrl: '/assets/mock-product-2.png',
      },
      {
        id: '6',
        name: 'Zero G',
        brand: { name: 'Fischer', slug: 'Fischer' },
        chips: ['Tour', 'Sci'],
        awards: [
          { name: 'green', color: 'green' },
          { name: 'smart', color: 'silver' },
          { name: 'pro', color: 'silver' },
        ],
        firstInfo: 'Larg. centro: 64mm',
        secondInfo: 'Peso: 780gr',
        imageUrl: '/assets/mock-product-3.png',
      },
      {
        id: '7',
        name: 'Zero G',
        brand: { name: 'Lange', slug: 'Lange' },
        chips: ['Tour', 'Sci'],
        awards: [
          { name: 'green', color: 'green' },
          { name: 'smart', color: 'silver' },
          { name: 'pro', color: 'silver' },
        ],
        testedPreview: 'TESTED',
        firstInfo: 'Larg. centro: 64mm',
        secondInfo: 'Peso: 780gr',
        imageUrl: '/assets/mock-product-1.png',
      },
      {
        id: '8',
        name: 'Orb freebird',
        brand: { name: 'Fischer', slug: 'Fischer' },
        chips: ['Tour', 'Sci'],
        awards: [{ name: 'green', color: 'green' }],
        firstInfo: 'Larg. centro: 64mm',
        secondInfo: 'Peso: 780gr',
        imageUrl: '/assets/mock-product-2.png',
      },
      {
        id: '9',
        name: 'Zero G',
        brand: { name: 'Lange', slug: 'Lange' },
        chips: ['Tour', 'Sci'],
        awards: [
          { name: 'smart', color: 'silver' },
          { name: 'pro', color: 'silver' },
        ],
        testedPreview: 'TESTED',
        firstInfo: 'Larg. centro: 64mm',
        secondInfo: 'Peso: 780gr',
        imageUrl: '/assets/mock-product-3.png',
      },
      {
        id: '10',
        name: 'Orb freebird',
        brand: { name: 'Dalbello', slug: 'Dalbello' },
        chips: ['Tour', 'Sci'],
        awards: [],
        testedPreview: 'TESTED',
        firstInfo: 'Larg. centro: 64mm',
        secondInfo: 'Peso: 780gr',
        imageUrl: '/assets/mock-sci.png',
      },
      {
        id: '11',
        name: 'Zero G',
        brand: { name: 'Fischer', slug: 'Fischer' },
        chips: ['Tour', 'Sci'],
        awards: [],
        firstInfo: 'Larg. centro: 64mm',
        secondInfo: 'Peso: 780gr',
        imageUrl: '/assets/mock-sci.png',
      },
      {
        id: '21',
        name: 'Zero G',
        brand: { name: 'Dalbello', slug: 'Dalbello' },
        chips: ['Tour', 'Sci'],
        awards: [
          { name: 'green', color: 'green' },
          { name: 'pro', color: 'silver' },
        ],
        testedPreview: 'TESTED',
        firstInfo: 'Larg. centro: 64mm',
        secondInfo: 'Peso: 780gr',
        imageUrl: '/assets/mock-product-1.png',
      },
      {
        id: '22',
        name: 'Orb freebird',
        brand: { name: 'Lange', slug: 'Lange' },
        chips: ['Tour', 'Sci'],
        awards: [{ name: 'smart', color: 'silver' }],
        firstInfo: 'Larg. centro: 64mm',
        secondInfo: 'Peso: 780gr',
        imageUrl: '/assets/mock-product-2.png',
        supermatch: true,
      },
      {
        id: '23',
        name: 'Orb freebird',
        brand: { name: 'Lange', slug: 'Lange' },
        chips: ['Tour', 'Sci'],
        awards: [{ name: 'pro', color: 'silver' }],
        firstInfo: 'Larg. centro: 64mm',
        secondInfo: 'Peso: 780gr',
        imageUrl: '/assets/mock-product-3.png',
      },
      {
        id: '24',
        name: 'Zero G',
        brand: { name: 'Dalbello', slug: 'Dalbello' },
        chips: ['Tour', 'Sci'],
        awards: [
          { name: 'green', color: 'green' },
          { name: 'smart', color: 'silver' },
          { name: 'pro', color: 'silver' },
        ],
        firstInfo: 'Larg. centro: 64mm',
        secondInfo: 'Peso: 780gr',
        imageUrl: '/assets/mock-product-1.png',
        supermatch: true,
      },
      {
        id: '25',
        name: 'Orb freebird',
        brand: { name: 'Fischer', slug: 'Fischer' },
        chips: ['Tour', 'Sci'],
        awards: [
          { name: 'green', color: 'green' },
          { name: 'smart', color: 'silver' },
          { name: 'pro', color: 'silver' },
        ],
        firstInfo: 'Larg. centro: 64mm',
        secondInfo: 'Peso: 780gr',
        imageUrl: '/assets/mock-product-2.png',
      },
      {
        id: '26',
        name: 'Zero G',
        brand: { name: 'Fischer', slug: 'Fischer' },
        chips: ['Tour', 'Sci'],
        awards: [
          { name: 'green', color: 'green' },
          { name: 'smart', color: 'silver' },
          { name: 'pro', color: 'silver' },
        ],
        firstInfo: 'Larg. centro: 64mm',
        secondInfo: 'Peso: 780gr',
        imageUrl: '/assets/mock-product-3.png',
      },
      {
        id: '27',
        name: 'Zero G',
        brand: { name: 'Lange', slug: 'Lange' },
        chips: ['Tour', 'Sci'],
        awards: [
          { name: 'green', color: 'green' },
          { name: 'smart', color: 'silver' },
          { name: 'pro', color: 'silver' },
        ],
        testedPreview: 'TESTED',
        firstInfo: 'Larg. centro: 64mm',
        secondInfo: 'Peso: 780gr',
        imageUrl: '/assets/mock-product-1.png',
      },
      {
        id: '28',
        name: 'Orb freebird',
        brand: { name: 'Fischer', slug: 'Fischer' },
        chips: ['Tour', 'Sci'],
        awards: [{ name: 'green', color: 'green' }],
        firstInfo: 'Larg. centro: 64mm',
        secondInfo: 'Peso: 780gr',
        imageUrl: '/assets/mock-product-2.png',
      },
      {
        id: '29',
        name: 'Zero G',
        brand: { name: 'Lange', slug: 'Lange' },
        chips: ['Tour', 'Sci'],
        awards: [
          { name: 'smart', color: 'silver' },
          { name: 'pro', color: 'silver' },
        ],
        testedPreview: 'TESTED',
        firstInfo: 'Larg. centro: 64mm',
        secondInfo: 'Peso: 780gr',
        imageUrl: '/assets/mock-product-3.png',
      },
      {
        id: '210',
        name: 'Orb freebird',
        brand: { name: 'Dalbello', slug: 'Dalbello' },
        chips: ['Tour', 'Sci'],
        awards: [],
        testedPreview: 'TESTED',
        firstInfo: 'Larg. centro: 64mm',
        secondInfo: 'Peso: 780gr',
        imageUrl: '/assets/mock-sci.png',
      },
      {
        id: '211',
        name: 'Zero G',
        brand: { name: 'Fischer', slug: 'Fischer' },
        chips: ['Tour', 'Sci'],
        awards: [],
        firstInfo: 'Larg. centro: 64mm',
        secondInfo: 'Peso: 780gr',
        imageUrl: '/assets/mock-sci.png',
      },
      {
        id: '31',
        name: 'Zero G',
        brand: { name: 'Dalbello', slug: 'Dalbello' },
        chips: ['Tour', 'Sci'],
        awards: [
          { name: 'green', color: 'green' },
          { name: 'pro', color: 'silver' },
        ],
        testedPreview: 'TESTED',
        firstInfo: 'Larg. centro: 64mm',
        secondInfo: 'Peso: 780gr',
        imageUrl: '/assets/mock-product-1.png',
      },
      {
        id: '32',
        name: 'Orb freebird',
        brand: { name: 'Lange', slug: 'Lange' },
        chips: ['Tour', 'Sci'],
        awards: [{ name: 'smart', color: 'silver' }],
        firstInfo: 'Larg. centro: 64mm',
        secondInfo: 'Peso: 780gr',
        imageUrl: '/assets/mock-product-2.png',
        supermatch: true,
      },
      {
        id: '33',
        name: 'Orb freebird',
        brand: { name: 'Lange', slug: 'Lange' },
        chips: ['Tour', 'Sci'],
        awards: [{ name: 'pro', color: 'silver' }],
        firstInfo: 'Larg. centro: 64mm',
        secondInfo: 'Peso: 780gr',
        imageUrl: '/assets/mock-product-3.png',
      },
      {
        id: '34',
        name: 'Zero G',
        brand: { name: 'Dalbello', slug: 'Dalbello' },
        chips: ['Tour', 'Sci'],
        awards: [
          { name: 'green', color: 'green' },
          { name: 'smart', color: 'silver' },
          { name: 'pro', color: 'silver' },
        ],
        firstInfo: 'Larg. centro: 64mm',
        secondInfo: 'Peso: 780gr',
        imageUrl: '/assets/mock-product-1.png',
        supermatch: true,
      },
      {
        id: '35',
        name: 'Orb freebird',
        brand: { name: 'Fischer', slug: 'Fischer' },
        chips: ['Tour', 'Sci'],
        awards: [
          { name: 'green', color: 'green' },
          { name: 'smart', color: 'silver' },
          { name: 'pro', color: 'silver' },
        ],
        firstInfo: 'Larg. centro: 64mm',
        secondInfo: 'Peso: 780gr',
        imageUrl: '/assets/mock-product-2.png',
      },
      {
        id: '36',
        name: 'Zero G',
        brand: { name: 'Fischer', slug: 'Fischer' },
        chips: ['Tour', 'Sci'],
        awards: [
          { name: 'green', color: 'green' },
          { name: 'smart', color: 'silver' },
          { name: 'pro', color: 'silver' },
        ],
        firstInfo: 'Larg. centro: 64mm',
        secondInfo: 'Peso: 780gr',
        imageUrl: '/assets/mock-product-3.png',
      },
      {
        id: '37',
        name: 'Zero G',
        brand: { name: 'Lange', slug: 'Lange' },
        chips: ['Tour', 'Sci'],
        awards: [
          { name: 'green', color: 'green' },
          { name: 'smart', color: 'silver' },
          { name: 'pro', color: 'silver' },
        ],
        testedPreview: 'TESTED',
        firstInfo: 'Larg. centro: 64mm',
        secondInfo: 'Peso: 780gr',
        imageUrl: '/assets/mock-product-1.png',
      },
      {
        id: '38',
        name: 'Orb freebird',
        brand: { name: 'Fischer', slug: 'Fischer' },
        chips: ['Tour', 'Sci'],
        awards: [{ name: 'green', color: 'green' }],
        firstInfo: 'Larg. centro: 64mm',
        secondInfo: 'Peso: 780gr',
        imageUrl: '/assets/mock-product-2.png',
      },
      {
        id: '39',
        name: 'Zero G',
        brand: { name: 'Lange', slug: 'Lange' },
        chips: ['Tour', 'Sci'],
        awards: [
          { name: 'smart', color: 'silver' },
          { name: 'pro', color: 'silver' },
        ],
        testedPreview: 'TESTED',
        firstInfo: 'Larg. centro: 64mm',
        secondInfo: 'Peso: 780gr',
        imageUrl: '/assets/mock-product-3.png',
      },
      {
        id: '310',
        name: 'Orb freebird',
        brand: { name: 'Dalbello', slug: 'Dalbello' },
        chips: ['Tour', 'Sci'],
        awards: [],
        testedPreview: 'TESTED',
        firstInfo: 'Larg. centro: 64mm',
        secondInfo: 'Peso: 780gr',
        imageUrl: '/assets/mock-sci.png',
      },
      {
        id: '311',
        name: 'Zero G',
        brand: { name: 'Fischer', slug: 'Fischer' },
        chips: ['Tour', 'Sci'],
        awards: [],
        firstInfo: 'Larg. centro: 64mm',
        secondInfo: 'Peso: 780gr',
        imageUrl: '/assets/mock-sci.png',
      },
    ],
  },
  decorators: [
    // SEE: https://github.com/remix-run/remix/discussions/6273#discussioncomment-5914448
    (Story) => {
      const RemixStub = createRemixStub([
        {
          path: '/',
          element: (
            <div>
              <Story />
            </div>
          ),
        },
      ])
      return <RemixStub />
    },
  ],
} satisfies Meta<typeof ProductWithFilters>

export default meta
type Story = StoryObj<typeof meta>

export const Primary: Story = {}
